class ProfileQuestion {
  const ProfileQuestion({
    required this.id,
    required this.question,
    required this.isText,
    this.options,
    this.theme,
  });

  final String id;
  final String question;
  final bool isText;
  final List<String>? options;
  final String? theme;
}

const List<ProfileQuestion> profileQuestions = [
  ProfileQuestion(
    id: 'q1',
    question: 'Quel est ton prénom ?',
    isText: true,
    theme: 'Identité',
  ),
  ProfileQuestion(
    id: 'q2',
    question: 'Quel est ton deuxième prénom ?',
    isText: true,
    theme: 'Identité',
  ),
  ProfileQuestion(
    id: 'q3',
    question: 'Quelle est ta date de naissance ?',
    isText: true,
    theme: 'Identité',
  ),
  ProfileQuestion(
    id: 'q4',
    question: 'Quel est ton signe astrologique ?',
    isText: true,
    theme: 'Identité',
  ),
  ProfileQuestion(
    id: 'q5',
    question: 'Dans quelle ville es-tu né(e) ?',
    isText: true,
    theme: 'Identité',
  ),
  ProfileQuestion(
    id: 'q6',
    question: 'Quelle est ta couleur préférée ?',
    isText: false,
    options: ['Bleu', 'Rouge', 'Vert', 'Noir'],
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q7',
    question: 'Ton plat préféré ?',
    isText: true,
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q8',
    question: 'Ton dessert préféré ?',
    isText: true,
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q9',
    question: 'Ton film préféré ?',
    isText: true,
    theme: 'Loisirs',
  ),
  ProfileQuestion(
    id: 'q10',
    question: 'Ta série du moment ?',
    isText: true,
    theme: 'Loisirs',
  ),
  ProfileQuestion(
    id: 'q11',
    question: 'Ton sport préféré ?',
    isText: true,
    theme: 'Loisirs',
  ),
  ProfileQuestion(
    id: 'q12',
    question: 'Tu préfères la mer ou la montagne ?',
    isText: false,
    options: ['Mer', 'Montagne', 'Les deux', 'Aucun des deux'],
    theme: 'Voyage',
  ),
  ProfileQuestion(
    id: 'q13',
    question: 'Ton pays rêvé ?',
    isText: true,
    theme: 'Voyage',
  ),
  ProfileQuestion(
    id: 'q14',
    question: 'Ta ville préférée ?',
    isText: true,
    theme: 'Voyage',
  ),
  ProfileQuestion(
    id: 'q15',
    question: 'Ta boisson préférée ?',
    isText: false,
    options: ['Eau', 'Café', 'Thé', 'Soda'],
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q16',
    question: 'Tu es plutôt matin ou soir ?',
    isText: false,
    options: ['Matin', 'Soir', 'Les deux', 'Ni l’un ni l’autre'],
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q17',
    question: 'Ton animal préféré ?',
    isText: true,
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q18',
    question: 'Ton fruit préféré ?',
    isText: true,
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q19',
    question: 'Ta saison préférée ?',
    isText: false,
    options: ['Printemps', 'Été', 'Automne', 'Hiver'],
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q20',
    question: 'Ton artiste musical préféré ?',
    isText: true,
    theme: 'Culture',
  ),
  ProfileQuestion(
    id: 'q21',
    question: 'Ton style musical favori ?',
    isText: true,
    theme: 'Culture',
  ),
  ProfileQuestion(
    id: 'q22',
    question: 'Ton livre préféré ?',
    isText: true,
    theme: 'Culture',
  ),
  ProfileQuestion(
    id: 'q23',
    question: 'Ton jeu vidéo préféré ?',
    isText: true,
    theme: 'Loisirs',
  ),
  ProfileQuestion(
    id: 'q24',
    question: 'Ton passe-temps du dimanche ?',
    isText: true,
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q25',
    question: 'Ton café tu le prends comment ?',
    isText: false,
    options: ['Sans sucre', 'Avec sucre', 'Avec lait', 'Je ne bois pas de café'],
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q26',
    question: 'Ton pire défaut selon toi ?',
    isText: true,
    theme: 'Personnalité',
  ),
  ProfileQuestion(
    id: 'q27',
    question: 'Ta plus grande qualité ?',
    isText: true,
    theme: 'Personnalité',
  ),
  ProfileQuestion(
    id: 'q28',
    question: 'Plutôt introverti ou extraverti ?',
    isText: false,
    options: ['Introverti', 'Extraverti', 'Ambiverti', 'Je ne sais pas'],
    theme: 'Personnalité',
  ),
  ProfileQuestion(
    id: 'q29',
    question: 'Ta devise de vie ?',
    isText: true,
    theme: 'Personnalité',
  ),
  ProfileQuestion(
    id: 'q30',
    question: 'Ton plus grand rêve ?',
    isText: true,
    theme: 'Aspirations',
  ),
  ProfileQuestion(
    id: 'q31',
    question: 'Ton métier rêvé ?',
    isText: true,
    theme: 'Aspirations',
  ),
  ProfileQuestion(
    id: 'q32',
    question: 'Plutôt sucré ou salé ?',
    isText: false,
    options: ['Sucré', 'Salé', 'Les deux', 'Aucun'],
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q33',
    question: 'Ta marque préférée ?',
    isText: true,
    theme: 'Style',
  ),
  ProfileQuestion(
    id: 'q34',
    question: 'Ton style vestimentaire ?',
    isText: true,
    theme: 'Style',
  ),
  ProfileQuestion(
    id: 'q35',
    question: 'Ton parfum préféré ?',
    isText: true,
    theme: 'Style',
  ),
  ProfileQuestion(
    id: 'q36',
    question: 'Ta matière scolaire préférée ?',
    isText: true,
    theme: 'Souvenirs',
  ),
  ProfileQuestion(
    id: 'q37',
    question: 'Ton souvenir d’enfance préféré ?',
    isText: true,
    theme: 'Souvenirs',
  ),
  ProfileQuestion(
    id: 'q38',
    question: 'Ta pire bêtise enfant ?',
    isText: true,
    theme: 'Souvenirs',
  ),
  ProfileQuestion(
    id: 'q39',
    question: 'Ton dessin animé préféré ?',
    isText: true,
    theme: 'Souvenirs',
  ),
  ProfileQuestion(
    id: 'q40',
    question: 'Ton héros préféré ?',
    isText: true,
    theme: 'Culture',
  ),
  ProfileQuestion(
    id: 'q41',
    question: 'Ton super-pouvoir rêvé ?',
    isText: true,
    theme: 'Fun',
  ),
  ProfileQuestion(
    id: 'q42',
    question: 'Plutôt chat ou chien ?',
    isText: false,
    options: ['Chat', 'Chien', 'Les deux', 'Aucun'],
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q43',
    question: 'Plutôt Netflix ou YouTube ?',
    isText: false,
    options: ['Netflix', 'YouTube', 'Les deux', 'Aucun'],
    theme: 'Loisirs',
  ),
  ProfileQuestion(
    id: 'q44',
    question: 'Ton jeu de société préféré ?',
    isText: true,
    theme: 'Loisirs',
  ),
  ProfileQuestion(
    id: 'q45',
    question: 'Ton plat que tu sais le mieux cuisiner ?',
    isText: true,
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q46',
    question: 'Ton objectif de l’année ?',
    isText: true,
    theme: 'Aspirations',
  ),
  ProfileQuestion(
    id: 'q47',
    question: 'Ton geste d’affection préféré ?',
    isText: true,
    theme: 'Relations',
  ),
  ProfileQuestion(
    id: 'q48',
    question: 'Ton moment préféré de la journée ?',
    isText: true,
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q49',
    question: 'Ta routine du matin ?',
    isText: true,
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q50',
    question: 'Plutôt improv ou planification ?',
    isText: false,
    options: ['Improvisation', 'Planification', 'Un peu des deux', 'Ça dépend'],
    theme: 'Personnalité',
  ),
  ProfileQuestion(
    id: 'q51',
    question: 'Ton lieu préféré pour te détendre ?',
    isText: true,
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q52',
    question: 'Ton meilleur ami s’appelle ?',
    isText: true,
    theme: 'Relations',
  ),
  ProfileQuestion(
    id: 'q53',
    question: 'Ton événement préféré de l’année ?',
    isText: true,
    theme: 'Souvenirs',
  ),
  ProfileQuestion(
    id: 'q54',
    question: 'Ta peur numéro 1 ?',
    isText: true,
    theme: 'Personnalité',
  ),
  ProfileQuestion(
    id: 'q55',
    question: 'Ton type de vacances idéal ?',
    isText: true,
    theme: 'Voyage',
  ),
  ProfileQuestion(
    id: 'q56',
    question: 'Ton moyen de transport préféré ?',
    isText: false,
    options: ['Voiture', 'Train', 'Avion', 'Vélo'],
    theme: 'Voyage',
  ),
  ProfileQuestion(
    id: 'q57',
    question: 'Tu préfères cuisiner ou commander ?',
    isText: false,
    options: ['Cuisiner', 'Commander', 'Les deux', 'Aucun'],
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q58',
    question: 'Ton film doudou ?',
    isText: true,
    theme: 'Culture',
  ),
  ProfileQuestion(
    id: 'q59',
    question: 'Ta chanson qui te motive ?',
    isText: true,
    theme: 'Culture',
  ),
  ProfileQuestion(
    id: 'q60',
    question: 'Ton meilleur voyage ?',
    isText: true,
    theme: 'Voyage',
  ),
  ProfileQuestion(
    id: 'q61',
    question: 'Ta série préférée de tous les temps ?',
    isText: true,
    theme: 'Loisirs',
  ),
  ProfileQuestion(
    id: 'q62',
    question: 'Ta cuisine préférée ?',
    isText: false,
    options: ['Italienne', 'Japonaise', 'Française', 'Marocaine'],
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q63',
    question: 'Plutôt thé ou café ?',
    isText: false,
    options: ['Thé', 'Café', 'Les deux', 'Aucun'],
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q64',
    question: 'Ton snack préféré ?',
    isText: true,
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q65',
    question: 'Ton application préférée ?',
    isText: true,
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q66',
    question: 'Ton emoji préféré ?',
    isText: true,
    theme: 'Fun',
  ),
  ProfileQuestion(
    id: 'q67',
    question: 'Ton souvenir de fête préféré ?',
    isText: true,
    theme: 'Souvenirs',
  ),
  ProfileQuestion(
    id: 'q68',
    question: 'Ton lieu de sortie favori ?',
    isText: true,
    theme: 'Relations',
  ),
  ProfileQuestion(
    id: 'q69',
    question: 'Ton cadeau parfait ?',
    isText: true,
    theme: 'Relations',
  ),
  ProfileQuestion(
    id: 'q70',
    question: 'Ton rendez-vous idéal ?',
    isText: true,
    theme: 'Relations',
  ),
  ProfileQuestion(
    id: 'q71',
    question: 'Ton type de film préféré ?',
    isText: false,
    options: ['Comédie', 'Action', 'Drame', 'Science-fiction'],
    theme: 'Culture',
  ),
  ProfileQuestion(
    id: 'q72',
    question: 'Plutôt pizza ou burger ?',
    isText: false,
    options: ['Pizza', 'Burger', 'Les deux', 'Aucun'],
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q73',
    question: 'Ta pizza préférée ?',
    isText: true,
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q74',
    question: 'Ton burger idéal ?',
    isText: true,
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q75',
    question: 'Ton lieu préféré en ville ?',
    isText: true,
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q76',
    question: 'Ton week-end parfait ?',
    isText: true,
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q77',
    question: 'Ta citation favorite ?',
    isText: true,
    theme: 'Personnalité',
  ),
  ProfileQuestion(
    id: 'q78',
    question: 'Ton achat le plus utile ?',
    isText: true,
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q79',
    question: 'Ton achat le plus inutile ?',
    isText: true,
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q80',
    question: 'Ta tradition familiale ?',
    isText: true,
    theme: 'Relations',
  ),
  ProfileQuestion(
    id: 'q81',
    question: 'Ton meilleur souvenir de voyage ?',
    isText: true,
    theme: 'Voyage',
  ),
  ProfileQuestion(
    id: 'q82',
    question: 'Ton plat d’enfance ?',
    isText: true,
    theme: 'Souvenirs',
  ),
  ProfileQuestion(
    id: 'q83',
    question: 'Ta boisson chaude préférée ?',
    isText: false,
    options: ['Chocolat chaud', 'Café', 'Thé', 'Infusion'],
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q84',
    question: 'Ton dessert de fête préféré ?',
    isText: true,
    theme: 'Souvenirs',
  ),
  ProfileQuestion(
    id: 'q85',
    question: 'Ton endroit préféré à la maison ?',
    isText: true,
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q86',
    question: 'Ton film que tu peux revoir 10 fois ?',
    isText: true,
    theme: 'Culture',
  ),
  ProfileQuestion(
    id: 'q87',
    question: 'Ta chanson qui te rend heureux ?',
    isText: true,
    theme: 'Culture',
  ),
  ProfileQuestion(
    id: 'q88',
    question: 'Ton meilleur souvenir d’amitié ?',
    isText: true,
    theme: 'Relations',
  ),
  ProfileQuestion(
    id: 'q89',
    question: 'Ton rêve fou ?',
    isText: true,
    theme: 'Aspirations',
  ),
  ProfileQuestion(
    id: 'q90',
    question: 'Ton objectif à 5 ans ?',
    isText: true,
    theme: 'Aspirations',
  ),
  ProfileQuestion(
    id: 'q91',
    question: 'Ta plus grande fierté ?',
    isText: true,
    theme: 'Personnalité',
  ),
  ProfileQuestion(
    id: 'q92',
    question: 'Ta couleur de vêtements préférée ?',
    isText: false,
    options: ['Noir', 'Blanc', 'Couleurs vives', 'Pastel'],
    theme: 'Style',
  ),
  ProfileQuestion(
    id: 'q93',
    question: 'Ton style de chaussures préféré ?',
    isText: true,
    theme: 'Style',
  ),
  ProfileQuestion(
    id: 'q94',
    question: 'Plutôt salé ou épicé ?',
    isText: false,
    options: ['Salé', 'Épicé', 'Les deux', 'Aucun'],
    theme: 'Préférences',
  ),
  ProfileQuestion(
    id: 'q95',
    question: 'Ta destination week-end idéale ?',
    isText: true,
    theme: 'Voyage',
  ),
  ProfileQuestion(
    id: 'q96',
    question: 'Ton festival préféré ?',
    isText: true,
    theme: 'Culture',
  ),
  ProfileQuestion(
    id: 'q97',
    question: 'Ton hobby créatif ?',
    isText: true,
    theme: 'Loisirs',
  ),
  ProfileQuestion(
    id: 'q98',
    question: 'Ta manière préférée de te relaxer ?',
    isText: true,
    theme: 'Habitudes',
  ),
  ProfileQuestion(
    id: 'q99',
    question: 'Ton émission TV préférée ?',
    isText: true,
    theme: 'Culture',
  ),
  ProfileQuestion(
    id: 'q100',
    question: 'Ton mantra du moment ?',
    isText: true,
    theme: 'Personnalité',
  ),
];
